openapi: "3.0.0"
info:
  description: "Semester project for 7th semester at Aalborg University"
  version: "1.0.0"
  title: "Offloading"
servers:
  - url: https://localhost:8080

components:
  schemas:
    job:
      type: object
      properties:
        name:
          type: string
        id:
          type: integer
          format: i64
          default: 0
  securitySchemes:
    oAuth2Password:
      type: oauth2
      description: See https://developers.getbase.com/docs/rest/articles/oauth2/requests
      flows:
        password:
          tokenUrl: http://localhost:9000/oauth/token
          scopes: {}

# Step 2 - apply security globally...
security:
  - oAuthNoScope: []

paths:
  /jobs:
    get:
      description: Returns a job file
      operationId: jobsGet
      "parameters": [
        {
          "in": "query",
          "name": "name",
          "description": "Job object that needs to be added to the store",
          "required": true,
          "schema": {
            "$ref": '#/components/schemas/job'
          }
        }
      ]
      responses:
        '200':
          description: List of funky stuff
          content:
            application/json:
              schema:
                type: string
                format: binary
    post:
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                file:
                  type: string
                  format: binary
      responses:
        '200':
          description: unimplemented
          content:
            application/json:
              schema:
                type: integer