openapi: "3.0.0"
info:
  description: "Semester project for 7th semester at Aalborg University"
  version: "1.0.0"
  title: "Offloading"
servers:
  - url: https://localhost:8080

components:
  schemas:
    Job:
      type: object
      properties:
        id:
          type: integer
          format: i64
          default: 0
        name:
          type: string
        jobpath:
          type: string
        status:
          type: string
        assignedUser:
          type: string

    UserCredentials:
      type: object
      properties:
        username:
          type: string

paths:
  /jobs:
    get:
      description: Returns a job file
      operationId: jobsGet
      responses:
        '200':
          description: List of funky stuff
          content:
            application/json:
              schema:
                type: string
                format: binary
    post:
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                file:
                  type: string
                  format: binary
      responses:
        '200':
          description: unimplemented
          content:
            application/json:
              schema:
                type: integer

  /jobs/{jobId}:
    delete:
      description: Deletes a job
      operationId: deleteJob
      responses:
        '200':
          description: Job Deleted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Job'
      parameters:
      - name: jobId
        in: path
        description: Job to be deleted
        required: true
        schema:
          type: integer
          format: int64

  /users:
    post:
      description: Creates a user
      operationId: createUser
      responses:
        '200':
          description: User Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserCredentials'
      requestBody:
        description: Create new user
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserCredentials'

  /users/{userId}:
    delete:
      description: Deletes a user
      operationId: deleteUser
      responses:
        '200':
          description: User Deleted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserCredentials'
      parameters:
      - name: userId
        in: path
        description: User to be deleted
        required: true
        schema:
          type: integer
          format: int64

  /users/{userId}/jobs:
    get:
      description: Returns all jobs assigned to current user
      operationId: getJobsForUser
      parameters:
      - name: userId
        in: path
        description: Id of user to filter jobs by
        required: true
        schema:
          type: integer
          format: int64
      responses:
        '200':
          description: List of jobs for selected user
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Job'

